using System.Security.Cryptography.X509Certificates;
using myfirst.Models;

namespace myfirst.Services
{
    class OrderService
    {
         public List<OrderModel> GetCompletedOrders(List<OrderModel> orders)
        {
            var completedOrders = orders
                .Where(o => o.Status == OrderStatus.Completed)
                .ToList();

            return completedOrders;
        }

        // Calculates total revenue from completed orders
        public decimal GetTotalRevenue(List<OrderModel> orders)
        {
            decimal totalRevenue = orders
                .Where(o => o.Status == OrderStatus.Completed)
                .Sum(o => o.OrderAmount);

            return totalRevenue;
        }
        // Generated by Copilot
       public OrderModel? GetFirstFailed(List<OrderModel> orders)
       {
                OrderModel? order=orders
                     .FirstOrDefault(o => o.Status == OrderStatus.Failed);
               return order;
       }
       public List<OrderModel> ApplyDiscounts(List<OrderModel> orders)
        {
            return orders.Select(order =>
            {
                decimal discountPercentage = 0;

                if (order.IsVipCustomer)
                    discountPercentage += 0.10m;
                if (order.OrderAmount > 50000)
                    discountPercentage += 0.05m;

                order.Discount = order.OrderAmount * discountPercentage;

                return order;
            }).ToList();
            
        }
    }
}