using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace capstone_policy_management.Entities
{
    // Generated by Copilot
    [Table("policy")]
    public class Policy
    {
        [Column("id")]
        public int Id { get; set; }

        [Column("policy_code")]
        [Required(ErrorMessage = "Policy code is required.")]
        [StringLength(50, ErrorMessage = "Policy code cannot exceed 50 characters.")]
        public string PolicyCode { get; set; } = string.Empty;

        [Column("policy_name")]
        [Required(ErrorMessage = "Policy name is required.")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "Policy name must be between 3 and 150 characters.")]
        public string Name { get; set; } = string.Empty;

        [Column("premium_amount")]
        [Required(ErrorMessage = "Premium amount is required.")]
        [Range(0.01, 999999.99, ErrorMessage = "Premium amount must be greater than 0.")]
        public decimal PremiumAmount { get; set; }

        [Column("description")]
        public string? Description { get; set; }

        [Column("is_active")]
        public bool IsActive { get; set; } = true;

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

        [Column("updated_at")]
        public DateTime UpdatedAt { get; set; }
    }
}