using BackendApicalls.Models.DTOs;
using BackendApicalls.Repositories;
using BackendApicalls.Services.Interfaces;

namespace BackendApicalls.Services
{
    public class EmployeeService:IEmployeeService

    {

        private readonly EmployeeRepository employeeRepository;
        public EmployeeService(EmployeeRepository employeesRepository)
        {
            employeeRepository = employeesRepository;
        }
        public async Task<List<EmployeeDTO>> GetAllEmployeesAsync()
        {
            // Generated by Copilot
            var employees = await employeeRepository.GetAllAsync();
            return employees.Select(e => new EmployeeDTO
                {
                    Id = e.Id,
                    FirstName = e.FirstName,
                    LastName = e.LastName,
                    Experience = e.Experience,
                    City = e.City,
                    Department = e.Department
                }).ToList();
        }

        
    }
}