using BackendApicalls.Models.entities;
using Microsoft.EntityFrameworkCore;
using BackendApicalls.Data;
using BackendApicalls.Repositories.Interfaces;

namespace BackendApicalls.Repositories;

public class EmployeeRepository : IEmployeeRepository

{
    // Generated by Copilot
    private readonly AppDbContext dbContext;

        public EmployeeRepository(AppDbContext context)
        {
            dbContext = context;
        }

    public async Task<List<Employee>> GetAllAsync()
    {
        return await dbContext.Employees.ToListAsync();
    }

}
