using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace capstone_policy_management.Filters;

// Generated by Copilot
public class GlobalResponseFilter : IAsyncResultFilter
{
    public async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
    {
        var result = context.Result as ObjectResult;
        if (result != null)
        {
            
            var statusCode = result.StatusCode ?? 200;
            var standardResponse = new
            {
                StatusCode = statusCode,
                Data = result.Value,
                Message = statusCode >= 200 && statusCode < 300 ? "Request processed successfully" : "Request failed",
                TraceId = context.HttpContext.TraceIdentifier
            };
            context.Result = new JsonResult(standardResponse)
            {
                StatusCode = statusCode
            };
        }

        await next();
    }
}